### ISSUE TITLE
re-add the India headline and example of demonetization

### ISSUE THREAD

**Issue by moneyball** [hello-bitcoin/hello-bitcoin#14]
https://en.wikipedia.org/wiki/2016_Indian_banknote_demonetisation

**Comment by hello-bitcoin** [comment]
Added
https://docs.google.com/presentation/d/1i4Ipk3Z7NwdUEHzavx5K9SVAMs5s2dQWyfzauk98H80/edit#slide=id.g7ce559c105_0_134
